await import('./migrate.mjs');

import http from 'node:http';
import crypto from 'node:crypto';
import { Pool } from 'pg';

const PORT=Number(process.env.PORT||8787), BUILD=process.env.SOURCE_BUILD||'COMMUNICATION_OS_RUNTIME_0.2.0', DATABASE_URL=process.env.DATABASE_URL;
if(!DATABASE_URL) throw new Error('DATABASE_URL is required');
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false}});
const id=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
const transitions={OFFERED:['ROUTING','REJECTED','CANCELLED','BLOCKED'],ROUTING:['QUEUED','RINGING','FAILED','BLOCKED'],QUEUED:['RINGING','CANCELLED','BLOCKED'],RINGING:['CONNECTED','MISSED','REJECTED','FAILED'],CONNECTED:['ACTIVE','TRANSFERRING','COMPLETED','FAILED'],ACTIVE:['TRANSFERRING','COMPLETED','FAILED'],TRANSFERRING:['RINGING','ACTIVE','FAILED']};
function send(res,status,body,headers={}){const h={'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-credentials':'true',...headers};if(process.env.CORS_ORIGIN)h['access-control-allow-origin']=process.env.CORS_ORIGIN;res.writeHead(status,h);res.end(JSON.stringify(body));}
function cookie(req,n){const m=(req.headers.cookie||'').match(new RegExp(`(?:^|; )${n}=([^;]+)`));return m?decodeURIComponent(m[1]):null;}
async function auth(req){const sid=cookie(req,'afagh_session');if(!sid)return null;const r=await pool.query('SELECT session_id,subject_id,display_name,tenant_id,workspace_id,roles,permissions,expires_at,revoked_at FROM sessions WHERE session_id=$1',[sid]);if(!r.rowCount)return null;const s=r.rows[0];if(s.revoked_at||new Date(s.expires_at)<=new Date())return null;return s;}
async function audit(s,correlation_id,outcome,resource,action){await pool.query('INSERT INTO audit_events(event_id,request_id,actor_subject_id,tenant_id,workspace_id,event_type,resource,action,outcome,timestamp) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,now())',[id(),correlation_id,s?.subject_id||'anonymous',s?.tenant_id||'unknown',s?.workspace_id||'unknown','COMMUNICATION_RUNTIME',resource,action,outcome]);}
async function persistEvidence(e){await pool.query('INSERT INTO communication_evidence(evidence_id,evidence_type,source,verifier,state,integrity,provenance,correlation_id,source_build,generated_at,verified_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[e.evidence_id,e.evidence_type,e.source,e.verifier,e.state,e.integrity,e.provenance,e.correlation_id,e.source_build,e.generated_at,e.verified_at]);return e;}
async function evidence(correlation_id,state='CONTROLLED'){const e={evidence_id:id(),evidence_type:'communication_runtime',source:'afagh-communication-os-runtime',verifier:'runtime-contract-engine',state,integrity:'UNSIGNED_CONTROLLED',provenance:'postgres-backed-server-generated',correlation_id,source_build:BUILD,generated_at:now(),verified_at:null};return persistEvidence(e);}
async function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}})});}
async function policy(b,s){const required=['identity_class','capability','resource','data_class','action','region','assurance','policy_version'];if(!s)return {decision:'DENY',reason:'AUTHENTICATION_REQUIRED'};if(required.some(k=>!b[k]))return {decision:'DENY',reason:'MISSING_AUTHORITATIVE_CONTEXT'};if(!['IRAN','CHINA'].includes(b.region))return {decision:'DENY',reason:'REGION_NOT_ALLOWED'};const permissions=s.permissions||[];const requiredPermission=b.action==='read'?'office:read':b.action==='write'?'office:write':'office:admin';if(!permissions.includes(requiredPermission))return {decision:'DENY',reason:'PERMISSION_DENIED'};return {decision:'ALLOW',reason:'POLICY_MATCH'};}
async function main(req,res){const u=new URL(req.url,`http://${req.headers.host}`);if(req.method==='OPTIONS')return send(res,204,{}, {'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});if(req.method==='GET'&&u.pathname==='/api/v1/communication/health')return send(res,200,{service:'afagh-communication-os-runtime',status:'CONTROLLED',build:BUILD,persistence:'POSTGRES',authentication:'P0-1_SESSION',evidence_persistence:'POSTGRES',production_verified:false});const s=await auth(req);
if(req.method==='GET'&&u.pathname==='/api/v1/communication/events'){if(!s)return send(res,401,{error:'AUTHENTICATION_REQUIRED'});const r=await pool.query('SELECT * FROM communication_events WHERE tenant_id=$1 AND workspace_id=$2 ORDER BY created_at DESC LIMIT 100',[s.tenant_id,s.workspace_id]);return send(res,200,{items:r.rows,count:r.rowCount,auth:'VALID'});}
if(req.method==='GET'&&u.pathname==='/api/v1/communication/actions'){if(!s)return send(res,401,{error:'AUTHENTICATION_REQUIRED'});const r=await pool.query('SELECT * FROM communication_actions ORDER BY created_at DESC LIMIT 100');return send(res,200,{items:r.rows,count:r.rowCount,auth:'VALID'});}
if(req.method!=='POST')return send(res,404,{error:'NOT_FOUND'});let b;try{b=await body(req)}catch{return send(res,400,{error:'INVALID_JSON'})};
if(u.pathname==='/api/v1/communication/policy/decide'){const correlation_id=b.correlation_id||id(),d=await policy(b,s),decision_id=id();await pool.query('INSERT INTO communication_policy_decisions(decision_id,subject,identity_class,capability,resource,data_class,action,tenant_id,workspace_id,region,assurance,policy_version,decision,reason,correlation_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)',[decision_id,s?.subject_id||'anonymous',b.identity_class,b.capability,b.resource,b.data_class,b.action,s?.tenant_id||null,s?.workspace_id||null,b.region,b.assurance,b.policy_version,d.decision,d.reason,correlation_id]);await audit(s,correlation_id,d.decision,'policy','decide');const ev=await evidence(correlation_id);return send(res,d.decision==='ALLOW'?200:403,{policy_decision:{decision_id,...d,correlation_id,policy_version:b.policy_version},evidence:ev});}
if(u.pathname==='/api/v1/communication/events'){if(!s)return send(res,401,{error:'AUTHENTICATION_REQUIRED'});const reqd=['communication_id','channel','actor','participants','tenant','workspace','region','correlation_id','policy_decision_id','authorization_decision_id'],missing=reqd.filter(k=>b[k]===undefined);if(missing.length)return send(res,422,{error:'CONTRACT_VIOLATION',contract:'COM-C03',missing});if(String(b.tenant)!==String(s.tenant_id)||String(b.workspace)!==String(s.workspace_id))return send(res,403,{error:'TENANT_WORKSPACE_MISMATCH'});const event_id=id();await pool.query('INSERT INTO communication_events(event_id,communication_id,channel,direction,actor,participants,tenant_id,workspace_id,region,lifecycle_state,correlation_id,policy_decision_id,authorization_decision_id,source_build) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)',[event_id,b.communication_id,b.channel,b.direction||null,JSON.stringify(b.actor),JSON.stringify(b.participants),s.tenant_id,s.workspace_id,b.region,'OFFERED',b.correlation_id,b.policy_decision_id,b.authorization_decision_id,BUILD]);await audit(s,b.correlation_id,'SUCCESS','communication_event','create');const ev=await evidence(b.correlation_id);return send(res,201,{event:{event_id,...b,tenant_id:s.tenant_id,workspace_id:s.workspace_id,lifecycle_state:'OFFERED',source_build:BUILD},evidence:ev});}
if(u.pathname.startsWith('/api/v1/communication/events/')&&u.pathname.endsWith('/transition')){if(!s)return send(res,401,{error:'AUTHENTICATION_REQUIRED'});const event_id=u.pathname.split('/')[5],r=await pool.query('SELECT * FROM communication_events WHERE event_id=$1',[event_id]);if(!r.rowCount)return send(res,404,{error:'EVENT_NOT_FOUND'});const e=r.rows[0],next=b.state;if(String(e.tenant_id)!==String(s.tenant_id)||String(e.workspace_id)!==String(s.workspace_id))return send(res,403,{error:'TENANT_WORKSPACE_MISMATCH'});if(!transitions[e.lifecycle_state]?.includes(next))return send(res,409,{error:'INVALID_STATE_TRANSITION',from:e.lifecycle_state,to:next});await pool.query('UPDATE communication_events SET lifecycle_state=$1,updated_at=now() WHERE event_id=$2',[next,event_id]);await audit(s,e.correlation_id,'SUCCESS','communication_event','transition');const ev=await evidence(e.correlation_id);return send(res,200,{event:{...e,lifecycle_state:next},evidence:ev});}
if(u.pathname==='/api/v1/communication/actions'){if(!s)return send(res,401,{error:'AUTHENTICATION_REQUIRED'});const reqd=['agent_id','risk_tier','policy_version','approval','tool_scope','model','correlation_id','idempotency_key'],missing=reqd.filter(k=>b[k]===undefined);if(missing.length)return send(res,422,{error:'CONTRACT_VIOLATION',contract:'COM-C04',missing});if(b.risk_tier!=='LOW'&&b.approval!=='HUMAN_APPROVED')return send(res,403,{error:'FAIL_CLOSED',reason:'APPROVAL_REQUIRED'});const action_id=id();try{await pool.query('INSERT INTO communication_actions(action_id,agent_id,action_state,risk_tier,policy_version,approval,tool_scope,model,correlation_id,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[action_id,b.agent_id,'APPROVED_ACTION',b.risk_tier,b.policy_version,b.approval,JSON.stringify(b.tool_scope),b.model,b.correlation_id,b.idempotency_key])}catch(e){if(e.code==='23505')return send(res,409,{error:'IDEMPOTENCY_CONFLICT'});throw e}await audit(s,b.correlation_id,'SUCCESS','ai_action','approve');const ev=await evidence(b.correlation_id);return send(res,201,{action:{action_id,...b,action_state:'APPROVED_ACTION'},evidence:ev});}
return send(res,404,{error:'NOT_FOUND'});}
http.createServer((req,res)=>main(req,res).catch(e=>{console.error(e);send(res,500,{error:'internal_error'});})).listen(PORT,()=>console.log(`Communication OS runtime :${PORT}`));
