import http from 'node:http';
import crypto from 'node:crypto';

const PORT=Number(process.env.PORT||8787); const sessions=new Map(); const POLICY_VERSION='p0-1.policy.v1';
const id=p=>`${p}_${crypto.randomUUID()}`; const now=()=>new Date().toISOString();
const json=(res,status,body,headers={})=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8',...headers});res.end(JSON.stringify(body));};
const cookie=(req,name)=>{const m=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='));return m?decodeURIComponent(m.slice(name.length+1)):null;};
const permission=a=>({read:'office:read',write:'office:write',admin:'office:admin'}[a]||`office:${a}`);
function auth(req){const sid=cookie(req,'afagh_session');const s=sid&&sessions.get(sid);if(!s)return{status:'UNKNOWN',session:null};if(s.revoked)return{status:'REVOKED',session:s};if(Date.now()>=Date.parse(s.expires_at))return{status:'EXPIRED',session:s};return{status:'VALID',session:s};}
function evidence(req,a){const u=new URL(req.url,'http://localhost'),resource=u.searchParams.get('resource')||'/api/v1/office',action=u.searchParams.get('action')||'read',ts=now(),s=a.session,allow=a.status==='VALID'&&(s?.permissions||[]).includes(permission(action));const requestId=id('req'),eventId=id('evt');return {schema_version:'p0-1.auth-evidence.v1',request:{request_id:requestId,method:req.method,resource,action,timestamp:ts},identity:{subject_id:s?.subject_id||'anonymous',display_name:s?.display_name||'Anonymous'},session:{session_id:s?.session_id||'unknown',status:a.status,issued_at:s?.issued_at||ts,expires_at:s?.expires_at||ts},context:{tenant_id:s?.tenant_id||'unknown',workspace_id:s?.workspace_id||'unknown'},authorization:{decision:allow?'ALLOW':'DENY',decision_id:id('dec'),roles:s?.roles||[],permissions:s?.permissions||[],policy_version:POLICY_VERSION},audit:{event_id:eventId,event_type:'AUTHORIZATION_DECISION',actor_subject_id:s?.subject_id||'anonymous',outcome:allow?'SUCCESS':'DENIED',timestamp:ts},evidence:{evidence_id:id('ev'),type:'AUTH_DECISION',source:'afagh-runtime/p0-1',integrity:'VERIFIED',created_at:ts}};}
function login(req,res){const sid=id('sess'),issued=now(),expires=new Date(Date.now()+3600000).toISOString();sessions.set(sid,{session_id:sid,subject_id:'demo.user',display_name:'AFAGH Demo User',tenant_id:'tenant.demo',workspace_id:'workspace.control',roles:['operator'],permissions:['office:read','office:write'],issued_at:issued,expires_at:expires,revoked:false});json(res,200,{mode:'demo',session_id:sid,expires_at:expires},{'set-cookie':`afagh_session=${encodeURIComponent(sid)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=3600`});}
const server=http.createServer((req,res)=>{if(req.method==='GET'&&req.url?.startsWith('/api/v1/auth/demo-login'))return login(req,res);if(req.method==='GET'&&(req.url==='/api/v1/auth/evidence'||req.url?.startsWith('/api/v1/auth/evidence?'))){const a=auth(req),b=evidence(req,a);return json(res,a.status==='VALID'&&b.authorization.decision==='ALLOW'?200:403,b,{'cache-control':'no-store'});}if(req.method==='GET'&&req.url==='/api/v1/health')return json(res,200,{service:'afagh-p0-1-runtime',status:'ok',mode:'demo',policy_version:POLICY_VERSION});return json(res,404,{error:'not_found'});});
server.listen(PORT,()=>console.log(`AFAGH P0-1 demo runtime listening on :${PORT}`));
