import http from 'node:http';
import crypto from 'node:crypto';
import { URL } from 'node:url';
import { Pool } from 'pg';
import { createRemoteJWKSet, jwtVerify } from 'jose';
import { serveStatic } from './static-handler.mjs';

const PORT=Number(process.env.PORT||8787),DATABASE_URL=process.env.DATABASE_URL,OIDC_ISSUER=process.env.OIDC_ISSUER,OIDC_CLIENT_ID=process.env.OIDC_CLIENT_ID,OIDC_CLIENT_SECRET=process.env.OIDC_CLIENT_SECRET,OIDC_REDIRECT_URI=process.env.OIDC_REDIRECT_URI,SESSION_TTL_SECONDS=Number(process.env.SESSION_TTL_SECONDS||3600),AUTH_FLOW_TTL_SECONDS=600,POLICY_VERSION='p0-1.policy.v2';
if(!DATABASE_URL||!OIDC_ISSUER||!OIDC_CLIENT_ID||!OIDC_CLIENT_SECRET||!OIDC_REDIRECT_URI)throw new Error('Missing required production environment configuration');
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.PGSSL==='disable'?false:{rejectUnauthorized:false}}),oidcIssuer=OIDC_ISSUER.replace(/\/$/,'');
let oidcConfig=null,jwks=null;
const id=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),json=(res,status,body,headers={})=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8',...headers});res.end(JSON.stringify(body));},cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return[x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]})),requiredPermission=a=>({read:'office:read',write:'office:write',admin:'office:admin'}[a]||`office:${a}`);
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS oidc_auth_flows (state TEXT PRIMARY KEY, verifier TEXT NOT NULL, nonce TEXT NOT NULL, tenant_id TEXT, workspace_id TEXT, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now())`);await pool.query(`CREATE INDEX IF NOT EXISTS oidc_auth_flows_expiry_idx ON oidc_auth_flows(expires_at)`);await pool.query(`DELETE FROM oidc_auth_flows WHERE expires_at<=now()`);}
async function discovery(){if(oidcConfig)return oidcConfig;const r=await fetch(`${oidcIssuer}/.well-known/openid-configuration`);if(!r.ok)throw new Error(`OIDC discovery failed: ${r.status}`);oidcConfig=await r.json();jwks=createRemoteJWKSet(new URL(oidcConfig.jwks_uri));return oidcConfig;}
async function login(req,res){const d=await discovery(),u0=new URL(req.url,'http://localhost'),tenant=u0.searchParams.get('tenant_id'),workspace=u0.searchParams.get('workspace_id'),state=crypto.randomBytes(32).toString('base64url'),verifier=crypto.randomBytes(32).toString('base64url'),nonce=crypto.randomBytes(32).toString('base64url'),challenge=crypto.createHash('sha256').update(verifier).digest('base64url');await pool.query('INSERT INTO oidc_auth_flows(state,verifier,nonce,tenant_id,workspace_id,expires_at) VALUES($1,$2,$3,$4,$5,now()+($6 || \' seconds\')::interval)',[state,verifier,nonce,tenant,workspace,AUTH_FLOW_TTL_SECONDS]);const u=new URL(d.authorization_endpoint);u.searchParams.set('response_type','code');u.searchParams.set('client_id',OIDC_CLIENT_ID);u.searchParams.set('redirect_uri',OIDC_REDIRECT_URI);u.searchParams.set('scope','openid profile email');u.searchParams.set('state',state);u.searchParams.set('nonce',nonce);u.searchParams.set('code_challenge',challenge);u.searchParams.set('code_challenge_method','S256');res.writeHead(302,{Location:u.toString(),'cache-control':'no-store'});res.end();}
async function callback(req,res){const u=new URL(req.url,'http://localhost'),state=u.searchParams.get('state'),code=u.searchParams.get('code');if(!state||!code)return json(res,400,{error:'invalid_oidc_callback'});const flow=await pool.query('SELECT state,verifier,nonce,tenant_id,workspace_id,expires_at FROM oidc_auth_flows WHERE state=$1',[state]);await pool.query('DELETE FROM oidc_auth_flows WHERE state=$1',[state]);if(!flow.rowCount||new Date(flow.rows[0].expires_at).getTime()<=Date.now())return json(res,400,{error:'invalid_or_expired_oidc_state'});const f=flow.rows[0],d=await discovery(),tokenRes=await fetch(d.token_endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:OIDC_REDIRECT_URI,client_id:OIDC_CLIENT_ID,client_secret:OIDC_CLIENT_SECRET,code_verifier:f.verifier})});if(!tokenRes.ok)return json(res,401,{error:'token_exchange_failed'});const tokens=await tokenRes.json();if(!tokens.id_token)return json(res,401,{error:'missing_id_token'});const {payload}=await jwtVerify(tokens.id_token,jwks,{issuer:oidcIssuer,audience:OIDC_CLIENT_ID,nonce:f.nonce}),subject=String(payload.sub),displayName=String(payload.name||payload.preferred_username||payload.email||subject);const m=await pool.query('SELECT tenant_id,workspace_id,roles,permissions FROM tenant_memberships WHERE subject_id=$1 ORDER BY tenant_id,workspace_id',[subject]);if(!m.rowCount)return json(res,403,{error:'tenant_membership_required'});let membership=null;if(f.tenant_id||f.workspace_id){membership=m.rows.find(x=>String(x.tenant_id)===String(f.tenant_id)&&String(x.workspace_id)===String(f.workspace_id));if(!membership)return json(res,403,{error:'requested_tenant_workspace_not_authorized'});}else if(m.rowCount===1){membership=m.rows[0];}else{return json(res,409,{error:'tenant_workspace_selection_required'});}const sid=id();await pool.query("INSERT INTO sessions(session_id,subject_id,display_name,tenant_id,workspace_id,roles,permissions,issued_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,now(),now()+($8 || ' seconds')::interval)",[sid,subject,displayName,membership.tenant_id,membership.workspace_id,membership.roles,membership.permissions,SESSION_TTL_SECONDS]);res.writeHead(302,{'set-cookie':`afagh_session=${encodeURIComponent(sid)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${SESSION_TTL_SECONDS}`,Location:'/auth-evidence.html','cache-control':'no-store'});res.end();}
async function logout(req,res){const sid=cookies(req).afagh_session;if(sid)await pool.query('UPDATE sessions SET revoked_at=now() WHERE session_id=$1',[sid]);json(res,200,{status:'signed_out'},{'set-cookie':'afagh_session=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0'});}
async function authenticate(req){const sid=cookies(req).afagh_session;if(!sid)return{status:'UNKNOWN',session:null};const r=await pool.query('SELECT session_id,subject_id,display_name,tenant_id,workspace_id,roles,permissions,issued_at,expires_at,revoked_at FROM sessions WHERE session_id=$1',[sid]);if(!r.rowCount)return{status:'UNKNOWN',session:null};const s=r.rows[0];if(s.revoked_at)return{status:'REVOKED',session:s};if(new Date(s.expires_at).getTime()<=Date.now())return{status:'EXPIRED',session:s};return{status:'VALID',session:s};}
async function audit(actor,tenant,workspace,outcome,requestId,resource,action){const eventId=id(),timestamp=now();await pool.query('INSERT INTO audit_events(event_id,request_id,actor_subject_id,tenant_id,workspace_id,event_type,resource,action,outcome,timestamp) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[eventId,requestId,actor||'anonymous',tenant||'unknown',workspace||'unknown','AUTHORIZATION_DECISION',resource,action,outcome,timestamp]);return{event_id:eventId,event_type:'AUTHORIZATION_DECISION',actor_subject_id:actor||'anonymous',outcome,timestamp};}
async function evidence(req,res){const auth=await authenticate(req),u=new URL(req.url,'http://localhost'),resource=u.searchParams.get('resource')||'/api/v1/office',action=u.searchParams.get('action')||'read',requestId=id(),ts=now(),s=auth.session,allow=auth.status==='VALID'&&(s.permissions||[]).includes(requiredPermission(action)),auditEvent=await audit(s?.subject_id,s?.tenant_id,s?.workspace_id,allow?'SUCCESS':'DENIED',requestId,resource,action),body={schema_version:'p0-1.auth-evidence.v2',request:{request_id:requestId,method:req.method,resource,action,timestamp:ts},identity:{subject_id:s?.subject_id||'anonymous',display_name:s?.display_name||'Anonymous'},session:{session_id:s?.session_id||'unknown',status:auth.status,issued_at:s?.issued_at?new Date(s.issued_at).toISOString():ts,expires_at:s?.expires_at?new Date(s.expires_at).toISOString():ts},context:{tenant_id:s?.tenant_id||'unknown',workspace_id:s?.workspace_id||'unknown'},authorization:{decision:allow?'ALLOW':'DENY',decision_id:id(),roles:s?.roles||[],permissions:s?.permissions||[],policy_version:POLICY_VERSION},audit:auditEvent,evidence:{evidence_id:id(),type:'AUTH_DECISION',source:'afagh-runtime/p0-1',integrity:'SERVER_GENERATED_UNSEALED',created_at:ts,verification_state:'PENDING_EXTERNAL_VERIFIER'}};json(res,allow?200:403,body,{'cache-control':'no-store'});}
await init();
const server=http.createServer(async(req,res)=>{try{if(req.method==='GET'&&req.url==='/api/v1/auth/login')return login(req,res);if(req.method==='GET'&&req.url?.startsWith('/api/v1/auth/callback'))return callback(req,res);if(req.method==='POST'&&req.url==='/api/v1/auth/logout')return logout(req,res);if(req.method==='GET'&&(req.url==='/api/v1/auth/evidence'||req.url?.startsWith('/api/v1/auth/evidence?')))return evidence(req,res);if(req.method==='GET'&&req.url==='/api/v1/health')return json(res,200,{service:'afagh-p0-1-runtime',status:'ok',mode:'production',policy_version:POLICY_VERSION,oidc_state:'POSTGRES',nonce_validation:true,tenant_selection:'EXPLICIT_OR_SINGLE_MEMBERSHIP',evidence_verification:'PENDING_EXTERNAL_VERIFIER'});if(await serveStatic(req,res))return;return json(res,404,{error:'not_found'});}catch(e){console.error(e);return json(res,500,{error:'internal_error'});}});
server.listen(PORT,()=>console.log(`AFAGH P0-1 production runtime listening on :${PORT}`));
